version: "3.1"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    image: nlp-text
    container_name: nlp-text
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ".:/home/work"
      - ".jupyter:/root/.jupyter"
    ports:
    - "8080:8080"
    tty: true
    command: jupyter lab --ip=0.0.0.0 --port=8080 --allow-root --NotebookApp.token='' --no-browser